id: I83222489
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:38:50+00:00'
last_modified: '2022-06-08T11:48:18.555293+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01617
  title: ཟབ་ཆོས་ནི་གུ་ཆོས་དྲུག་གི་བརྒྱུད་འདེབས་ཉུང་འདུས་བདེ་ཆེན་འབེབས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2CE1:
      image_group_id: I00KG02872
      title: ''
      total_pages: 10
      order: 1
      base_file: 2CE1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
