id: P009547
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:37:29.177181
source_metadata:
  id: bdr:W00KG01617
  title: ཟབ་ཆོས་ནི་གུ་ཆོས་དྲུག་གི་བརྒྱུད་འདེབས་ཉུང་འདུས་བདེ་ཆེན་འབེབས་པ
  author: ''
  volumes:
    deda4ee12d9744289d7c942fe9aa78b5:
      image_group_id: I00KG02872
      title: ''
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
